### ISSUE TITLE
How do I start the example?

### ISSUE THREAD

**Issue by domoritz** [duckdb-wasm-examples/sveltekit-typescript#4]
I've tried running `npm I && npm run dev` but then when I open the web-server, I get `Not found (did you mean /sveltekit-typescript/?)`. I get similar results with `npm run preview`. Do I need to run anything else?

**Comment by bmschmidt** [comment]
Navigate to `http://localhost:1922/sveltekit-typescript/`, not `http://localhost:1922`.

Because the website is at `duckdb-wasm-examples.github.io/sveltekit-typescript`, the URLs are set up to use that prefix on localhost, too. It's possible to not use the prefix on localhost, but this way is a little easier. Probably merits a description in the README somewhere.

**Comment by bmschmidt** [comment]
Closing: https://github.com/duckdb-wasm-examples/sveltekit-typescript/commit/65d4a1d77074e886d6370e4e7f236dddaebc8fad
